version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"

