source 'https://rubygems.org'

gem 'rake'
gem 'rake_dependencies'
gem 'rake_terraform'
gem 'rake_circle_ci'
gem 'rake_github'
gem 'rake_ssh'
gem 'rake_gpg'
gem 'confidante'
gem 'rspec'
gem 'awspec'
gem 'git'
gem 'semantic'
