source 'https://rubygems.org'

gem 'rake', '~> 12.3'
gem 'rake_dependencies', '~> 0.23'
gem 'rake_terraform', '~> 0.29'
gem 'lino', '~> 1.1'
gem 'rspec', '~> 3.8'
gem 'awspec', '~> 1.17'
gem 'git', '~> 1.5'
gem 'semantic', '~> 1.6'
