---
region: 'eu-west-2'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"
vpc_cidr: "10.1.0.0/16"
private_network_cidr: '10.0.0.0/8'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

service_task_network_mode: "host"
service_task_pid_mode: "host"

service_name: "service-without-lb"
service_image: "nginx"
service_command:
  - "nginx"
  - "-g"
  - "daemon off;"
service_port: 80
service_desired_count: 2
service_deployment_maximum_percent: 150
service_deployment_minimum_healthy_percent: 25
service_health_check_grace_period_seconds: 0

attach_to_load_balancer: false

associate_default_security_group: true
default_security_group_ingress_cidrs:
  - "10.0.0.0/8"
default_security_group_egress_cidrs:
  - "0.0.0.0/0"

register_in_service_discovery: false
service_discovery_create_registry: true

include_log_group: true
log_group_retention: 0

service_volumes:
  - name: "temporary"
    host_path: "/some/path"

scheduling_strategy: "REPLICA"

placement_constraints:
  - type: "memberOf"
    expression: "attribute:ecs.availability-zone in [eu-west-2a, eu-west-2b]"

domain_name: 'infrablocks.click'
public_zone_id: "Z08829023L5IPIQBJOX63"
private_zone_id: 'Z0211739BXR21FNN139O'

cluster_name: 'test-cluster'
cluster_instance_ssh_public_key_path: "%{cwd}/config/secrets/keys/cluster/ssh.public"
cluster_instance_type: 't2.medium'

cluster_minimum_size: 1
cluster_maximum_size: 3
cluster_desired_capacity: 2

alb_health_check_path: "/"
elb_health_check_target: "HTTP:80/"
elb_https_allow_cidrs:
  - '10.1.0.0/16'
