---
region: 'eu-west-2'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"
vpc_cidr: "10.1.0.0/16"
private_network_cidr: '10.0.0.0/8'

component: 'test'

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

service_task_container_definitions: ''
service_task_network_mode: "host"

service_name: "service-without-lb"
service_image: "nginx"
service_command:
  - "nginx"
  - "-g"
  - "daemon off;"
service_port: 80
service_desired_count: 2
service_deployment_maximum_percent: 150
service_deployment_minimum_healthy_percent: 25
service_role: ''

attach_to_load_balancer: 'no'
service_elb_name: ''
target_group_arn: ''

include_log_group: 'yes'

service_volumes:
  - name: "temporary"
    host_path: "/some/path"

scheduling_strategy: "REPLICA"

placement_constraints:
  - type: "memberOf"
    expression: "attribute:ecs.availability-zone in [eu-west-2a, eu-west-2b]"

domain_name: 'greasedscone.uk'
public_zone_id: 'Z4Q2X3ESOZT4N'
private_zone_id: 'Z2CDAFD23Q10HO'

cluster_name: 'test-cluster'
cluster_instance_ssh_public_key_path: "%{hiera('project_directory')}/config/secrets/keys/cluster/ssh.public"
cluster_instance_type: 't2.medium'

cluster_minimum_size: 1
cluster_maximum_size: 3
cluster_desired_capacity: 2

service_certificate_body: "%{hiera('project_directory')}/config/secrets/certificates/cert.pem"
service_certificate_private_key: "%{hiera('project_directory')}/config/secrets/certificates/ssl.key"

alb_health_check_path: "/"
elb_health_check_target: "HTTP:80/"
elb_https_allow_cidrs:
  - "%{hiera('public_address')}/32"
